title = "Singapore Government Digital Services"
linkPrefix = "/gds-hive"
resumeMailAddress = "hiring@ida-gds.com"

[[navLinks]]
href = "/careers/"
title = "Careers"

[[navLinks]]
href = "https://medium.com/singapore-gds/"
title = "Blog"
external=true

[[navLinks]]
href = "/"
title = "GDS-HIVE"
