blogTitle = "GDS-HIVE"
authorName = "GDS"
linkPrefix = "/gds-hive"
resumeMailAddress = "mailto:hiring@ida-gds.com"

[[navLinks]]
href = "/jobs/"
title = "Jobs"

[[navLinks]]
href = "/projects/"
title = "Projects"

[[navLinks]]
href = "/"
title = "GDS-HIVE"
