title = "Government Digital Services, Singapore"
linkPrefix = "/gds-hive"
resumeMailAddress = "hiring@gds-gov.tech"

[[navLinks]]
href = "/careers/"
title = "Careers"

[[navLinks]]
href = "https://blog.gds-gov.tech/"
title = "Blog"
external=true

[[navLinks]]
href = "/"
title = "GDS-HIVE"
