[[projects]]
title = "Business Grants Portal"
subtitle = "Business Grants Portal brings government grants for businesses into one place, so it’s easier to find and apply for the grants you need."
url = "https://www.businessgrants.gov.sg"
image = "./images/bgp.png"

[[projects]]
title = "data.gov.sg"
subtitle = "The Singapore government’s one-stop portal to publicly-available datasets from 70 public agencies."
url = "https://data.gov.sg/"
image = "./images/data.png"

[[projects]]
title = "myResponder"
subtitle = "The myResponder Mobile App alerts volunteers to nearby Cardiac Arrest Cases to render first aid before ambulance arrival."
url = "https://www.raedi.sg/"
image = "./images/myresponder.png"